# Generated by Django 4.0.1 on 2022-02-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
